---

dir_home_user_mq: "/home/mqm"
dir_host_tmp: "/tmp"
dir_ha: "/HA"
dir_ha_logs: "/HA/log"
dir_create_files: "{{ dir_home_user_mq }}"
dir_mq_medios: "{{ dir_create_files }}/mq"
dir_mq_scripts: "{{ dir_create_files }}/scripts"
dir_mq_mqmhome: "{{ dir_create_files }}/mqmhome"
dir_mq_services: "{{ dir_create_files }}/services"
binary_name: "IBM_MQ_9.1_LINUX_X86-64_TRIAL.tar.gz"
dir_mq_mqprofile: "{{ dir_create_files }}/mqprofile"
dir_mq_mqserver: "{{ dir_mq_medios }}/MQServer"
sysctlconf: "/etc/sysctl.conf"
limitsconf: "/etc/security/limits.conf"
binaries_location: "{{ dir_mq_medios }}/{{ binary_name }}"
mqmhome_zip: "{{ dir_mq_mqmhome }}/mqmhome.zip"
scripts_zip: "{{ dir_mq_scripts }}/scripts.zip"
services_zip: "{{ dir_mq_scripts }}/services.zip"
usr_bin: "/usr/local/bin"
system_loc: "/etc/systemd/system"
opt_loc: "/opt/mqm"
opt_bin: "/opt/mqm/bin"
